version: "3.8"
services:
  api:
    build:
      context: ./
      target: production
    volumes:
      - .:/src
    command: npm start
    ports:
      - "80:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
